name: breaking_news
description: "A NEWS App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  lottie:
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.0+4
  get_time_ago: ^2.0.0
  intl: ^0.19.0
  blur: ^4.0.0
  photo_view: ^0.15.0
  share_plus: ^10.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0




flutter:
  uses-material-design: true

  assets:
    - assets/


